---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: false
    rubocop_config:
      inherit_from:
        - .rubocop.yml
  SpaceAroundErbTag:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  SelfClosingTag:
    enabled: true
